module-task3
htmlacademy-nodejs/66361-buy-and-sell-3 pull request #2
Opened 2021-08-02 21:08 UTC by Grachya

2021-08-03 10:24 UTC, copperkraft requested changes

2021-08-03 10:24 UTC, copperkraft commented on src/service/cli/generate.js
> +  let formatNum = String(num).padStart(2, `0`);
По правилам академии (с которым я согласен) нужно использовать const для переменных, значение которых не изменяется.

2021-08-03 10:24 UTC, copperkraft commented on src/service/cli/generate.js
> +const CATEGORIES = [`Книги`, `Разное`, `Посуда`, `Игры`, `Животные`, `Журналы`];
Я бы рекомендовал любые массивы больше 2-3 элементов писать "в столбик" (каждое значение на отдельной строке)

2021-08-03 10:24 UTC, copperkraft commented on src/service/cli/generate.js
> +      category: [CATEGORIES[getRandomInt(0, CATEGORIES.length - 1)]],
Я бы вынес практически всю логику из .map в отдельные функции. Притом не только повторяющуюся, а вообще всю. Как минимум стоит выделить функции для получения случайного элемента из массива и получения случайного элемента из объекта (OfferType)

2021-08-03 12:42 UTC, Grachya commented on src/service/cli/generate.js
> +  let formatNum = String(num).padStart(2, `0`);
Понял, поменяю

2021-08-03 12:42 UTC, Grachya commented on src/service/cli/generate.js
> +const CATEGORIES = [`Книги`, `Разное`, `Посуда`, `Игры`, `Животные`, `Журналы`];
Поменяю

2021-08-03 12:48 UTC, Grachya commented on src/service/cli/generate.js
> +      category: [CATEGORIES[getRandomInt(0, CATEGORIES.length - 1)]],
Тут не очень понятно.
То есть для каждого свойства вынести свою функцию?

getDescription()
getPicture()
getType()
getSum()

А для Category  и Title сделать общую универсальную фукнцию принимающую массив и выдающую случайный элемент из него?

getArrRandomElement(arr)

2021-08-04 21:17 UTC, Grachya commented on src/service/cli/generate.js
> +      category: [CATEGORIES[getRandomInt(0, CATEGORIES.length - 1)]],
Внес правки

2021-08-06 14:06 UTC, merged